-keep class io.github.supermonster003.autojs6.plugin.nodejs.NodeJsPluginInfoService { *; }
-keep class io.github.supermonster003.autojs6.plugin.nodejs.NodeJsPluginInfoService$* { *; }
-keep class org.autojs.plugin.common.api.** { *; }
-keep class org.autojs.plugin.nodejs.api.** { *; }
