#include "embedded_probe_metadata.h"

namespace autojs6::node_bridge {
namespace {

constexpr EmbeddedInlineProbeSelectorFlags inlineSelectorFlags(
        bool consoleStream,
        bool consoleShape,
        bool consoleReplaceRequested,
        bool consoleFamilyRequested,
        bool consoleFormatRequested,
        bool consoleRejectionRequested
) {
    return {
            true,
            true,
            true,
            consoleStream,
            consoleShape,
            consoleReplaceRequested,
            consoleFamilyRequested,
            consoleFormatRequested,
            consoleRejectionRequested,
            true,
            false,
            true,
    };
}

constexpr EmbeddedInlineProbeSelectorFlags inlineSelectorFlagsWithSchedulingRequested(
        bool consoleStream,
        bool consoleShape,
        bool consoleReplaceRequested,
        bool consoleFamilyRequested,
        bool consoleFormatRequested,
        bool consoleRejectionRequested
) {
    return {
            true,
            true,
            true,
            consoleStream,
            consoleShape,
            consoleReplaceRequested,
            consoleFamilyRequested,
            consoleFormatRequested,
            consoleRejectionRequested,
            true,
            true,
            true,
    };
}

bool selectorFlagsMatch(
        const EmbeddedInlineProbeSelectorFlags& lhs,
        const EmbeddedInlineProbeSelectorFlags& rhs
) {
    return lhs.jsResult == rhs.jsResult &&
           lhs.stdoutWriteRequested == rhs.stdoutWriteRequested &&
           lhs.consoleDiagnostics == rhs.consoleDiagnostics &&
           lhs.consoleStream == rhs.consoleStream &&
           lhs.consoleShape == rhs.consoleShape &&
           lhs.consoleReplaceRequested == rhs.consoleReplaceRequested &&
           lhs.consoleFamilyRequested == rhs.consoleFamilyRequested &&
           lhs.consoleFormatRequested == rhs.consoleFormatRequested &&
           lhs.consoleRejectionRequested == rhs.consoleRejectionRequested &&
           lhs.consoleUncaughtRequested == rhs.consoleUncaughtRequested &&
           lhs.schedulingRequested == rhs.schedulingRequested &&
           lhs.schedulingOrderRequested == rhs.schedulingOrderRequested;
}

constexpr EmbeddedInlineProbeMetadata kInlineProbeMetadata[] = {
        {
                EmbeddedLifecycleJsProbeKind::InlineConstant,
                "inline_constant",
                "v8.uv.inline_constant.lifecycle",
                "v8 uv inline constant lifecycle did not start",
                "timing.inline_constant.ms",
                "",
                "",
                inlineSelectorFlags(false, false, false, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineReturnValue,
                "inline_return_value",
                "v8.uv.inline_return_value.lifecycle",
                "v8 uv inline return value lifecycle did not start",
                "timing.inline_return_value.ms",
                "",
                "",
                inlineSelectorFlags(false, false, false, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineError,
                "inline_error",
                "v8.uv.inline_error.lifecycle",
                "v8 uv inline error lifecycle did not start",
                "timing.inline_error.ms",
                "",
                "",
                inlineSelectorFlags(true, false, false, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineOutput,
                "inline_output",
                "v8.uv.inline_output.lifecycle",
                "v8 uv inline output lifecycle did not start",
                "timing.inline_output.ms",
                "inline stdout probe",
                "inline stderr probe",
                inlineSelectorFlags(true, false, false, true, false, true),
                true,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineAsync,
                "inline_async",
                "v8.uv.inline_async.lifecycle",
                "v8 uv inline async lifecycle did not start",
                "timing.inline_async.ms",
                "",
                "",
                inlineSelectorFlags(true, false, false, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineCancel,
                "inline_cancel",
                "v8.uv.inline_cancel.lifecycle",
                "v8 uv inline cancel lifecycle did not start",
                "timing.inline_cancel.ms",
                "",
                "",
                inlineSelectorFlags(false, false, true, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineTimeout,
                "inline_timeout",
                "v8.uv.inline_timeout.lifecycle",
                "v8 uv inline timeout lifecycle did not start",
                "timing.inline_timeout.ms",
                "",
                "",
                inlineSelectorFlags(false, false, true, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineRepeatedProcess,
                "inline_repeated_process",
                "v8.uv.inline_repeated_process.lifecycle",
                "v8 uv inline repeated process lifecycle did not start",
                "timing.inline_repeated_process.ms",
                "",
                "",
                inlineSelectorFlags(false, false, true, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineBuiltinPolicy,
                "inline_builtin_policy",
                "v8.uv.inline_builtin_policy.lifecycle",
                "v8 uv inline builtin policy lifecycle did not start",
                "timing.inline_builtin_policy.ms",
                "",
                "",
                inlineSelectorFlags(false, true, false, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineRequireDenied,
                "inline_require_denied",
                "v8.uv.inline_require_denied.lifecycle",
                "v8 uv inline require denied lifecycle did not start",
                "timing.inline_require_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, false, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineNpmDenied,
                "inline_npm_denied",
                "v8.uv.inline_npm_denied.lifecycle",
                "v8 uv inline npm denied lifecycle did not start",
                "timing.inline_npm_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, true, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlinePackageJsonDenied,
                "inline_package_json_denied",
                "v8.uv.inline_package_json_denied.lifecycle",
                "v8 uv inline package.json denied lifecycle did not start",
                "timing.inline_package_json_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, false, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineNodeModulesDenied,
                "inline_node_modules_denied",
                "v8.uv.inline_node_modules_denied.lifecycle",
                "v8 uv inline node_modules denied lifecycle did not start",
                "timing.inline_node_modules_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, false, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineNativeAddonDenied,
                "inline_native_addon_denied",
                "v8.uv.inline_native_addon_denied.lifecycle",
                "v8 uv inline native addon denied lifecycle did not start",
                "timing.inline_native_addon_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, true, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineEsmDenied,
                "inline_esm_denied",
                "v8.uv.inline_esm_denied.lifecycle",
                "v8 uv inline ESM denied lifecycle did not start",
                "timing.inline_esm_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, true, false, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineDynamicImportDenied,
                "inline_dynamic_import_denied",
                "v8.uv.inline_dynamic_import_denied.lifecycle",
                "v8 uv inline dynamic import denied lifecycle did not start",
                "timing.inline_dynamic_import_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, true, false, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineWorkerDenied,
                "inline_worker_denied",
                "v8.uv.inline_worker_denied.lifecycle",
                "v8 uv inline worker denied lifecycle did not start",
                "timing.inline_worker_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, true, true, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineCapabilitySummary,
                "inline_capability_summary",
                "v8.uv.inline_capability_summary.lifecycle",
                "v8 uv inline capability summary lifecycle did not start",
                "timing.inline_capability_summary.ms",
                "",
                "",
                inlineSelectorFlags(true, true, true, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineFilesystemDenied,
                "inline_filesystem_denied",
                "v8.uv.inline_filesystem_denied.lifecycle",
                "v8 uv inline filesystem denied lifecycle did not start",
                "timing.inline_filesystem_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, true, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineChildProcessDenied,
                "inline_child_process_denied",
                "v8.uv.inline_child_process_denied.lifecycle",
                "v8 uv inline child_process denied lifecycle did not start",
                "timing.inline_child_process_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, true, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineNetworkDenied,
                "inline_network_denied",
                "v8.uv.inline_network_denied.lifecycle",
                "v8 uv inline network denied lifecycle did not start",
                "timing.inline_network_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, true, false, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlinePermissionsDenied,
                "inline_permissions_denied",
                "v8.uv.inline_permissions_denied.lifecycle",
                "v8 uv inline permissions denied lifecycle did not start",
                "timing.inline_permissions_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, true, true, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineAndroidBridgeDenied,
                "inline_android_bridge_denied",
                "v8.uv.inline_android_bridge_denied.lifecycle",
                "v8 uv inline Android bridge denied lifecycle did not start",
                "timing.inline_android_bridge_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, true, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineAutoJsApiDenied,
                "inline_autojs_api_denied",
                "v8.uv.inline_autojs_api_denied.lifecycle",
                "v8 uv inline AutoJs API denied lifecycle did not start",
                "timing.inline_autojs_api_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, true, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineConsoleBridgeDenied,
                "inline_console_bridge_denied",
                "v8.uv.inline_console_bridge_denied.lifecycle",
                "v8 uv inline console bridge denied lifecycle did not start",
                "timing.inline_console_bridge_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, false, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineJsonSocketDenied,
                "inline_json_socket_denied",
                "v8.uv.inline_json_socket_denied.lifecycle",
                "v8 uv inline JsonSocket denied lifecycle did not start",
                "timing.inline_json_socket_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, false, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineBinderDenied,
                "inline_binder_denied",
                "v8.uv.inline_binder_denied.lifecycle",
                "v8 uv inline Binder denied lifecycle did not start",
                "timing.inline_binder_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, false, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineUiBridgeDenied,
                "inline_ui_bridge_denied",
                "v8.uv.inline_ui_bridge_denied.lifecycle",
                "v8 uv inline UI bridge denied lifecycle did not start",
                "timing.inline_ui_bridge_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, false, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineAccessibilityDenied,
                "inline_accessibility_denied",
                "v8.uv.inline_accessibility_denied.lifecycle",
                "v8 uv inline accessibility denied lifecycle did not start",
                "timing.inline_accessibility_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, false, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineImagesDenied,
                "inline_images_denied",
                "v8.uv.inline_images_denied.lifecycle",
                "v8 uv inline images denied lifecycle did not start",
                "timing.inline_images_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, true, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineDialogsDenied,
                "inline_dialogs_denied",
                "v8.uv.inline_dialogs_denied.lifecycle",
                "v8 uv inline dialogs denied lifecycle did not start",
                "timing.inline_dialogs_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, true, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineSensorsDenied,
                "inline_sensors_denied",
                "v8.uv.inline_sensors_denied.lifecycle",
                "v8 uv inline sensors denied lifecycle did not start",
                "timing.inline_sensors_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, true, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineMediaCameraDenied,
                "inline_media_camera_denied",
                "v8.uv.inline_media_camera_denied.lifecycle",
                "v8 uv inline media/camera denied lifecycle did not start",
                "timing.inline_media_camera_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, true, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineStorageDenied,
                "inline_storage_denied",
                "v8.uv.inline_storage_denied.lifecycle",
                "v8 uv inline storage denied lifecycle did not start",
                "timing.inline_storage_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, false, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineShellDenied,
                "inline_shell_denied",
                "v8.uv.inline_shell_denied.lifecycle",
                "v8 uv inline shell denied lifecycle did not start",
                "timing.inline_shell_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, false, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineNotificationDenied,
                "inline_notification_denied",
                "v8.uv.inline_notification_denied.lifecycle",
                "v8 uv inline notification denied lifecycle did not start",
                "timing.inline_notification_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, false, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineClipboardDenied,
                "inline_clipboard_denied",
                "v8.uv.inline_clipboard_denied.lifecycle",
                "v8 uv inline clipboard denied lifecycle did not start",
                "timing.inline_clipboard_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, false, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineDeviceInfoDenied,
                "inline_device_info_denied",
                "v8.uv.inline_device_info_denied.lifecycle",
                "v8 uv inline device info denied lifecycle did not start",
                "timing.inline_device_info_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, true, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineVibrationDenied,
                "inline_vibration_denied",
                "v8.uv.inline_vibration_denied.lifecycle",
                "v8 uv inline vibration denied lifecycle did not start",
                "timing.inline_vibration_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, true, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineToastDenied,
                "inline_toast_denied",
                "v8.uv.inline_toast_denied.lifecycle",
                "v8 uv inline toast denied lifecycle did not start",
                "timing.inline_toast_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, true, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineFloatyDenied,
                "inline_floaty_denied",
                "v8.uv.inline_floaty_denied.lifecycle",
                "v8 uv inline floaty denied lifecycle did not start",
                "timing.inline_floaty_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, true, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineEventsDenied,
                "inline_events_denied",
                "v8.uv.inline_events_denied.lifecycle",
                "v8 uv inline events denied lifecycle did not start",
                "timing.inline_events_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, true, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineThreadsDenied,
                "inline_threads_denied",
                "v8.uv.inline_threads_denied.lifecycle",
                "v8 uv inline threads denied lifecycle did not start",
                "timing.inline_threads_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, false, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineTimersDenied,
                "inline_timers_denied",
                "v8.uv.inline_timers_denied.lifecycle",
                "v8 uv inline timers denied lifecycle did not start",
                "timing.inline_timers_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, false, true, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineWebViewDenied,
                "inline_webview_denied",
                "v8.uv.inline_webview_denied.lifecycle",
                "v8 uv inline webview denied lifecycle did not start",
                "timing.inline_webview_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, false, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineHttpDenied,
                "inline_http_denied",
                "v8.uv.inline_http_denied.lifecycle",
                "v8 uv inline http denied lifecycle did not start",
                "timing.inline_http_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, false, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineCryptoDenied,
                "inline_crypto_denied",
                "v8.uv.inline_crypto_denied.lifecycle",
                "v8 uv inline crypto denied lifecycle did not start",
                "timing.inline_crypto_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, false, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineOcrDenied,
                "inline_ocr_denied",
                "v8.uv.inline_ocr_denied.lifecycle",
                "v8 uv inline ocr denied lifecycle did not start",
                "timing.inline_ocr_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, false, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineMlAiDenied,
                "inline_ml_ai_denied",
                "v8.uv.inline_ml_ai_denied.lifecycle",
                "v8 uv inline ML/AI denied lifecycle did not start",
                "timing.inline_ml_ai_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, true, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineWebSocketDenied,
                "inline_websocket_denied",
                "v8.uv.inline_websocket_denied.lifecycle",
                "v8 uv inline WebSocket denied lifecycle did not start",
                "timing.inline_websocket_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, true, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineBluetoothDenied,
                "inline_bluetooth_denied",
                "v8.uv.inline_bluetooth_denied.lifecycle",
                "v8 uv inline Bluetooth denied lifecycle did not start",
                "timing.inline_bluetooth_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, true, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineNfcDenied,
                "inline_nfc_denied",
                "v8.uv.inline_nfc_denied.lifecycle",
                "v8 uv inline NFC denied lifecycle did not start",
                "timing.inline_nfc_denied.ms",
                "",
                "",
                inlineSelectorFlags(false, true, true, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineUsbDenied,
                "inline_usb_denied",
                "v8.uv.inline_usb_denied.lifecycle",
                "v8 uv inline USB denied lifecycle did not start",
                "timing.inline_usb_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, false, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineLocationDenied,
                "inline_location_denied",
                "v8.uv.inline_location_denied.lifecycle",
                "v8 uv inline location denied lifecycle did not start",
                "timing.inline_location_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, false, true, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineContactsDenied,
                "inline_contacts_denied",
                "v8.uv.inline_contacts_denied.lifecycle",
                "v8 uv inline contacts denied lifecycle did not start",
                "timing.inline_contacts_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, true, false, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineCalendarDenied,
                "inline_calendar_denied",
                "v8.uv.inline_calendar_denied.lifecycle",
                "v8 uv inline calendar denied lifecycle did not start",
                "timing.inline_calendar_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, true, false, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineSmsTelephonyDenied,
                "inline_sms_telephony_denied",
                "v8.uv.inline_sms_telephony_denied.lifecycle",
                "v8 uv inline SMS/telephony denied lifecycle did not start",
                "timing.inline_sms_telephony_denied.ms",
                "",
                "",
                inlineSelectorFlags(true, true, false, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineAccountDenied,
                "inline_account_denied",
                "v8.uv.inline_account_denied.lifecycle",
                "v8 uv inline account denied lifecycle did not start",
                "timing.inline_account_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, false, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlinePackageManagerDenied,
                "inline_package_manager_denied",
                "v8.uv.inline_package_manager_denied.lifecycle",
                "v8 uv inline package manager denied lifecycle did not start",
                "timing.inline_package_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, false, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineIntentActivityDenied,
                "inline_intent_activity_denied",
                "v8.uv.inline_intent_activity_denied.lifecycle",
                "v8 uv inline intent/activity denied lifecycle did not start",
                "timing.inline_intent_activity_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, false, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineBroadcastDenied,
                "inline_broadcast_denied",
                "v8.uv.inline_broadcast_denied.lifecycle",
                "v8 uv inline broadcast denied lifecycle did not start",
                "timing.inline_broadcast_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, false, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineContentProviderDenied,
                "inline_content_provider_denied",
                "v8.uv.inline_content_provider_denied.lifecycle",
                "v8 uv inline content provider denied lifecycle did not start",
                "timing.inline_content_provider_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, false, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineMediaStoreDenied,
                "inline_media_store_denied",
                "v8.uv.inline_media_store_denied.lifecycle",
                "v8 uv inline media store denied lifecycle did not start",
                "timing.inline_media_store_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, true, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineDownloadManagerDenied,
                "inline_download_manager_denied",
                "v8.uv.inline_download_manager_denied.lifecycle",
                "v8 uv inline download manager denied lifecycle did not start",
                "timing.inline_download_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, true, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineInputMethodDenied,
                "inline_input_method_denied",
                "v8.uv.inline_input_method_denied.lifecycle",
                "v8 uv inline input method denied lifecycle did not start",
                "timing.inline_input_method_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, true, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineAppOpsDenied,
                "inline_app_ops_denied",
                "v8.uv.inline_app_ops_denied.lifecycle",
                "v8 uv inline app ops denied lifecycle did not start",
                "timing.inline_app_ops_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, true, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlinePermissionManagerDenied,
                "inline_permission_manager_denied",
                "v8.uv.inline_permission_manager_denied.lifecycle",
                "v8 uv inline permission manager denied lifecycle did not start",
                "timing.inline_permission_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, false, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineSettingsDenied,
                "inline_settings_denied",
                "v8.uv.inline_settings_denied.lifecycle",
                "v8 uv inline settings denied lifecycle did not start",
                "timing.inline_settings_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, false, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlinePowerManagerDenied,
                "inline_power_manager_denied",
                "v8.uv.inline_power_manager_denied.lifecycle",
                "v8 uv inline power manager denied lifecycle did not start",
                "timing.inline_power_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, false, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineKeyguardDenied,
                "inline_keyguard_denied",
                "v8.uv.inline_keyguard_denied.lifecycle",
                "v8 uv inline keyguard denied lifecycle did not start",
                "timing.inline_keyguard_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, false, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineWallpaperDenied,
                "inline_wallpaper_denied",
                "v8.uv.inline_wallpaper_denied.lifecycle",
                "v8 uv inline wallpaper denied lifecycle did not start",
                "timing.inline_wallpaper_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, false, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineShortcutManagerDenied,
                "inline_shortcut_manager_denied",
                "v8.uv.inline_shortcut_manager_denied.lifecycle",
                "v8 uv inline shortcut manager denied lifecycle did not start",
                "timing.inline_shortcut_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, true, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineAlarmManagerDenied,
                "inline_alarm_manager_denied",
                "v8.uv.inline_alarm_manager_denied.lifecycle",
                "v8 uv inline alarm manager denied lifecycle did not start",
                "timing.inline_alarm_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, true, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineJobSchedulerDenied,
                "inline_job_scheduler_denied",
                "v8.uv.inline_job_scheduler_denied.lifecycle",
                "v8 uv inline job scheduler denied lifecycle did not start",
                "timing.inline_job_scheduler_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, true, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineWorkManagerDenied,
                "inline_work_manager_denied",
                "v8.uv.inline_work_manager_denied.lifecycle",
                "v8 uv inline work manager denied lifecycle did not start",
                "timing.inline_work_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, true, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineClipboardListenerDenied,
                "inline_clipboard_listener_denied",
                "v8.uv.inline_clipboard_listener_denied.lifecycle",
                "v8 uv inline clipboard listener denied lifecycle did not start",
                "timing.inline_clipboard_listener_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, false, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineNotificationListenerDenied,
                "inline_notification_listener_denied",
                "v8.uv.inline_notification_listener_denied.lifecycle",
                "v8 uv inline notification listener denied lifecycle did not start",
                "timing.inline_notification_listener_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, false, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineAccessibilityControlDenied,
                "inline_accessibility_control_denied",
                "v8.uv.inline_accessibility_control_denied.lifecycle",
                "v8 uv inline accessibility control denied lifecycle did not start",
                "timing.inline_accessibility_control_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, false, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineDevicePolicyDenied,
                "inline_device_policy_denied",
                "v8.uv.inline_device_policy_denied.lifecycle",
                "v8 uv inline device policy denied lifecycle did not start",
                "timing.inline_device_policy_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, true, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineUsageStatsDenied,
                "inline_usage_stats_denied",
                "v8.uv.inline_usage_stats_denied.lifecycle",
                "v8 uv inline usage stats denied lifecycle did not start",
                "timing.inline_usage_stats_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, true, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineVpnConnectivityDenied,
                "inline_vpn_connectivity_denied",
                "v8.uv.inline_vpn_connectivity_denied.lifecycle",
                "v8 uv inline vpn connectivity denied lifecycle did not start",
                "timing.inline_vpn_connectivity_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, true, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineWifiManagerDenied,
                "inline_wifi_manager_denied",
                "v8.uv.inline_wifi_manager_denied.lifecycle",
                "v8 uv inline wifi manager denied lifecycle did not start",
                "timing.inline_wifi_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, false, true, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineTelephonySubscriptionDenied,
                "inline_telephony_subscription_denied",
                "v8.uv.inline_telephony_subscription_denied.lifecycle",
                "v8 uv inline telephony subscription denied lifecycle did not start",
                "timing.inline_telephony_subscription_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, false, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineCameraManagerDenied,
                "inline_camera_manager_denied",
                "v8.uv.inline_camera_manager_denied.lifecycle",
                "v8 uv inline camera manager denied lifecycle did not start",
                "timing.inline_camera_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, false, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineAudioManagerDenied,
                "inline_audio_manager_denied",
                "v8.uv.inline_audio_manager_denied.lifecycle",
                "v8 uv inline audio manager denied lifecycle did not start",
                "timing.inline_audio_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, false, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlineDisplayManagerDenied,
                "inline_display_manager_denied",
                "v8.uv.inline_display_manager_denied.lifecycle",
                "v8 uv inline display manager denied lifecycle did not start",
                "timing.inline_display_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, true, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::InlinePrintManagerDenied,
                "inline_print_manager_denied",
                "v8.uv.inline_print_manager_denied.lifecycle",
                "v8 uv inline print manager denied lifecycle did not start",
                "timing.inline_print_manager_denied.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, true, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserSourceDescriptor,
                "user_source_descriptor",
                "v8.uv.user_source_descriptor.lifecycle",
                "v8 uv user source descriptor lifecycle did not start",
                "timing.user_source_descriptor.ms",
                "",
                "",
                inlineSelectorFlags(true, true, false, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserSourceSize,
                "user_source_size",
                "v8.uv.user_source_size.lifecycle",
                "v8 uv user source size lifecycle did not start",
                "timing.user_source_size.ms",
                "",
                "",
                inlineSelectorFlags(true, true, false, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserSourceEncoding,
                "user_source_encoding",
                "v8.uv.user_source_encoding.lifecycle",
                "v8 uv user source encoding lifecycle did not start",
                "timing.user_source_encoding.ms",
                "",
                "",
                inlineSelectorFlags(true, true, true, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserSourceName,
                "user_source_name",
                "v8.uv.user_source_name.lifecycle",
                "v8 uv user source name lifecycle did not start",
                "timing.user_source_name.ms",
                "",
                "",
                inlineSelectorFlags(true, true, true, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserSourceWrapper,
                "user_source_wrapper",
                "v8.uv.user_source_wrapper.lifecycle",
                "v8 uv user source wrapper lifecycle did not start",
                "timing.user_source_wrapper.ms",
                "",
                "",
                inlineSelectorFlags(true, true, true, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserSourceStrictMode,
                "user_source_strict_mode",
                "v8.uv.user_source_strict_mode.lifecycle",
                "v8 uv user source strict mode lifecycle did not start",
                "timing.user_source_strict_mode.ms",
                "",
                "",
                inlineSelectorFlags(true, true, true, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserSourceCapability,
                "user_source_capability",
                "v8.uv.user_source_capability.lifecycle",
                "v8 uv user source capability lifecycle did not start",
                "timing.user_source_capability.ms",
                "",
                "",
                inlineSelectorFlags(true, true, true, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserSourcePreflight,
                "user_source_preflight",
                "v8.uv.user_source_preflight.lifecycle",
                "v8 uv user source preflight lifecycle did not start",
                "timing.user_source_preflight.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, true, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::ControlledUserInlineConstant,
                "controlled_user_inline_constant",
                "v8.uv.controlled_user_inline_constant.lifecycle",
                "v8 uv controlled user inline constant lifecycle did not start",
                "timing.controlled_user_inline_constant.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(false, true, true, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::ControlledUserInlineStdout,
                "controlled_user_inline_stdout",
                "v8.uv.controlled_user_inline_stdout.lifecycle",
                "v8 uv controlled user inline stdout lifecycle did not start",
                "timing.controlled_user_inline_stdout.ms",
                "hello stdout\n",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, false, false, false, false),
                true,
        },
        {
                EmbeddedLifecycleJsProbeKind::ControlledUserInlineStderr,
                "controlled_user_inline_stderr",
                "v8.uv.controlled_user_inline_stderr.lifecycle",
                "v8 uv controlled user inline stderr lifecycle did not start",
                "timing.controlled_user_inline_stderr.ms",
                "",
                "hello stderr\n",
                inlineSelectorFlagsWithSchedulingRequested(true, false, false, false, false, true),
                true,
        },
        {
                EmbeddedLifecycleJsProbeKind::ControlledUserInlineReturnValue,
                "controlled_user_inline_return_value",
                "v8.uv.controlled_user_inline_return_value.lifecycle",
                "v8 uv controlled user inline return value lifecycle did not start",
                "timing.controlled_user_inline_return_value.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, false, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::ControlledUserInlineThrownError,
                "controlled_user_inline_thrown_error",
                "v8.uv.controlled_user_inline_thrown_error.lifecycle",
                "v8 uv controlled user inline thrown error lifecycle did not start",
                "timing.controlled_user_inline_thrown_error.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, false, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::ControlledUserInlinePromise,
                "controlled_user_inline_promise",
                "v8.uv.controlled_user_inline_promise.lifecycle",
                "v8 uv controlled user inline promise lifecycle did not start",
                "timing.controlled_user_inline_promise.ms",
                "42",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, false, true, false, false),
                true,
        },
        {
                EmbeddedLifecycleJsProbeKind::ControlledUserInlineAsyncOrdering,
                "controlled_user_inline_async_ordering",
                "v8.uv.controlled_user_inline_async_ordering.lifecycle",
                "v8 uv controlled user inline async ordering lifecycle did not start",
                "timing.controlled_user_inline_async_ordering.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, false, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::ControlledUserInlineSummary,
                "controlled_user_inline_summary",
                "v8.uv.controlled_user_inline_summary.lifecycle",
                "v8 uv controlled user inline summary lifecycle did not start",
                "timing.controlled_user_inline_summary.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, false, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserFileDescriptor,
                "user_file_descriptor",
                "v8.uv.user_file_descriptor.lifecycle",
                "v8 uv user file descriptor lifecycle did not start",
                "timing.user_file_descriptor.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, false, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserFileReadPolicy,
                "user_file_read_policy",
                "v8.uv.user_file_read_policy.lifecycle",
                "v8 uv user file read policy lifecycle did not start",
                "timing.user_file_read_policy.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, true, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserFilePathNormalization,
                "user_file_path_normalization",
                "v8.uv.user_file_path_normalization.lifecycle",
                "v8 uv user file path normalization lifecycle did not start",
                "timing.user_file_path_normalization.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, true, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserFileWorkingDirectory,
                "user_file_working_directory",
                "v8.uv.user_file_working_directory.lifecycle",
                "v8 uv user file working directory lifecycle did not start",
                "timing.user_file_working_directory.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, true, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserFileSourceLoading,
                "user_file_source_loading",
                "v8.uv.user_file_source_loading.lifecycle",
                "v8 uv user file source loading lifecycle did not start",
                "timing.user_file_source_loading.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, true, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserFileExecutionDryRun,
                "user_file_execution_dry_run",
                "v8.uv.user_file_execution_dry_run.lifecycle",
                "v8 uv user file execution dry-run lifecycle did not start",
                "timing.user_file_execution_dry_run.ms",
                "hello from embedded file dry-run\nv24.5.0\n",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, true, true, false, false),
                true,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserFileErrorStackFilename,
                "user_file_error_stack_filename",
                "v8.uv.user_file_error_stack_filename.lifecycle",
                "v8 uv user file error stack filename lifecycle did not start",
                "timing.user_file_error_stack_filename.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, true, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::UserFileExecutionSummary,
                "user_file_execution_summary",
                "v8.uv.user_file_execution_summary.lifecycle",
                "v8 uv user file execution summary lifecycle did not start",
                "timing.user_file_execution_summary.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, true, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedScriptRequest,
                "embedded_script_request",
                "v8.uv.embedded_script_request.lifecycle",
                "v8 uv embedded script request lifecycle did not start",
                "timing.embedded_script_request.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, false, true, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedScriptResult,
                "embedded_script_result",
                "v8.uv.embedded_script_result.lifecycle",
                "v8 uv embedded script result lifecycle did not start",
                "timing.embedded_script_result.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, false, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedScriptOutputEvent,
                "embedded_script_output_event",
                "v8.uv.embedded_script_output_event.lifecycle",
                "v8 uv embedded script output event lifecycle did not start",
                "timing.embedded_script_output_event.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, false, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedScriptError,
                "embedded_script_error",
                "v8.uv.embedded_script_error.lifecycle",
                "v8 uv embedded script error lifecycle did not start",
                "timing.embedded_script_error.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, false, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedScriptTimeout,
                "embedded_script_timeout",
                "v8.uv.embedded_script_timeout.lifecycle",
                "v8 uv embedded script timeout lifecycle did not start",
                "timing.embedded_script_timeout.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, false, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedScriptCancellation,
                "embedded_script_cancellation",
                "v8.uv.embedded_script_cancellation.lifecycle",
                "v8 uv embedded script cancellation lifecycle did not start",
                "timing.embedded_script_cancellation.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, false, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedScriptProcessIsolation,
                "embedded_script_process_isolation",
                "v8.uv.embedded_script_process_isolation.lifecycle",
                "v8 uv embedded script process isolation lifecycle did not start",
                "timing.embedded_script_process_isolation.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, false, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedScriptContract,
                "embedded_script_contract",
                "v8.uv.embedded_script_contract.lifecycle",
                "v8 uv embedded script contract lifecycle did not start",
                "timing.embedded_script_contract.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, false, true, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedMvpLifecycleReadiness,
                "embedded_mvp_lifecycle",
                "v8.uv.embedded_mvp_lifecycle.lifecycle",
                "v8 uv embedded MVP lifecycle readiness lifecycle did not start",
                "timing.embedded_mvp_lifecycle.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, false, true, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedMvpSourceInputReadiness,
                "embedded_mvp_source_input",
                "v8.uv.embedded_mvp_source_input.lifecycle",
                "v8 uv embedded MVP source input readiness lifecycle did not start",
                "timing.embedded_mvp_source_input.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, true, false, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedMvpOutputReadiness,
                "embedded_mvp_output",
                "v8.uv.embedded_mvp_output.lifecycle",
                "v8 uv embedded MVP output readiness lifecycle did not start",
                "timing.embedded_mvp_output.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, true, false, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedMvpErrorHandlingReadiness,
                "embedded_mvp_error_handling",
                "v8.uv.embedded_mvp_error_handling.lifecycle",
                "v8 uv embedded MVP error handling readiness lifecycle did not start",
                "timing.embedded_mvp_error_handling.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, true, false, true, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedMvpAsyncReadiness,
                "embedded_mvp_async",
                "v8.uv.embedded_mvp_async.lifecycle",
                "v8 uv embedded MVP async readiness lifecycle did not start",
                "timing.embedded_mvp_async.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, true, false, true, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedMvpTimeoutIsolationReadiness,
                "embedded_mvp_timeout_isolation",
                "v8.uv.embedded_mvp_timeout_isolation.lifecycle",
                "v8 uv embedded MVP timeout/isolation readiness lifecycle did not start",
                "timing.embedded_mvp_timeout_isolation.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, true, true, false, false),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedMvpSecurityPolicyReadiness,
                "embedded_mvp_security_policy",
                "v8.uv.embedded_mvp_security_policy.lifecycle",
                "v8 uv embedded MVP security policy readiness lifecycle did not start",
                "timing.embedded_mvp_security_policy.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, true, true, false, true),
                false,
        },
        {
                EmbeddedLifecycleJsProbeKind::EmbeddedMvpGoNoGoReadiness,
                "embedded_mvp_go_no_go",
                "v8.uv.embedded_mvp_go_no_go.lifecycle",
                "v8 uv embedded MVP go/no-go readiness lifecycle did not start",
                "timing.embedded_mvp_go_no_go.ms",
                "",
                "",
                inlineSelectorFlagsWithSchedulingRequested(true, true, true, true, true, false),
                false,
        },
};

}  // namespace

const EmbeddedInlineProbeMetadata* findEmbeddedInlineProbeMetadata(EmbeddedLifecycleJsProbeKind kind) {
    for (const auto& metadata : kInlineProbeMetadata) {
        if (metadata.kind == kind) {
            return &metadata;
        }
    }
    return nullptr;
}

const EmbeddedInlineProbeSelectorFlags* embeddedInlineProbeSelectorFlags(EmbeddedLifecycleJsProbeKind kind) {
    const auto* metadata = findEmbeddedInlineProbeMetadata(kind);
    return metadata == nullptr ? nullptr : &metadata->selectorFlags;
}

EmbeddedLifecycleJsProbeKind embeddedInlineProbeKindFromSelectorFlags(const EmbeddedInlineProbeSelectorFlags& flags) {
    for (const auto& metadata : kInlineProbeMetadata) {
        if (selectorFlagsMatch(metadata.selectorFlags, flags)) {
            return metadata.kind;
        }
    }
    return EmbeddedLifecycleJsProbeKind::None;
}

const char* embeddedInlineProbePayloadPrefix(EmbeddedLifecycleJsProbeKind kind) {
    const auto* metadata = findEmbeddedInlineProbeMetadata(kind);
    return metadata == nullptr ? nullptr : metadata->payloadPrefix;
}

const char* embeddedInlineProbeLogName(EmbeddedLifecycleJsProbeKind kind) {
    const auto* metadata = findEmbeddedInlineProbeMetadata(kind);
    return metadata == nullptr ? nullptr : metadata->logName;
}

const char* embeddedInlineProbeNotStartedDetail(EmbeddedLifecycleJsProbeKind kind) {
    const auto* metadata = findEmbeddedInlineProbeMetadata(kind);
    return metadata == nullptr ? nullptr : metadata->notStartedDetail;
}

const char* embeddedInlineProbeTimingKey(EmbeddedLifecycleJsProbeKind kind) {
    const auto* metadata = findEmbeddedInlineProbeMetadata(kind);
    return metadata == nullptr ? nullptr : metadata->timingKey;
}

const char* embeddedInlineProbeExpectedStdout(EmbeddedLifecycleJsProbeKind kind) {
    const auto* metadata = findEmbeddedInlineProbeMetadata(kind);
    return metadata == nullptr ? nullptr : metadata->expectedStdout;
}

const char* embeddedInlineProbeExpectedStderr(EmbeddedLifecycleJsProbeKind kind) {
    const auto* metadata = findEmbeddedInlineProbeMetadata(kind);
    return metadata == nullptr ? nullptr : metadata->expectedStderr;
}

bool embeddedInlineProbeStdoutCapture(EmbeddedLifecycleJsProbeKind kind) {
    const auto* metadata = findEmbeddedInlineProbeMetadata(kind);
    return metadata != nullptr && metadata->stdoutCapture;
}

}  // namespace autojs6::node_bridge
